debug: true
logging:
  path: E:/apocalypse/logs
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: druid
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/apocalypse_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
