#debug: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: druid
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/apocalypse_uac?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10000ms
    password: rockysaas@redis
  cloud:
    inetutils:
      ignored-interfaces: #忽略docker0网卡以及 veth开头的网卡
        - docker0
        - veth.*
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      log:
        switch-pid: true
    consul:
      enabled: true
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
        tags:
          - java
          - service
        health-check-path: ${server.servlet.context-path}/actuator/health
        instance-id: instance-${spring.cloud.client.ip-address}-${spring.application.name}-${server.port}
  cache:
    type: redis
    redis:
      time-to-live: 300000ms
