server:
  port: 38001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    gateway:
#      discovery:
#        locator:
#          enabled: true

  application:
    name: sidecar-node
sidecar:
  # 异构微服务的IP
  ip: 127.0.0.1
  # 异构微服务的端口
  port: 48060

  # 异构微服务的健康检查URL
  #health-check-url: http://localhost:8060/health.json
management:
  endpoint:
    health:
      show-details: always