debug: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: druid
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/apocalypse_idaas?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
  redis:
    database: 6
    host: localhost
    port: 6379
    timeout: 10000ms
    redisson:
      file: classpath:/redisson/redisson-dev.yaml
  cloud:
    inetutils:
      ignored-interfaces: #忽略docker0网卡以及 veth开头的网卡
        - docker0
        - veth.*
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      log:
        switch-pid: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
knife4j:
  production: false
  setting:
    enableAfterScript: true