swagger:
  enable: true
  title: Geek模块
  description: Geek相关接口
  version: 1.0.0
  base-package: com.apocalypse.example.geek.controller
server:
  port: 42001
  servlet:
    context-path: /geek-api
  tomcat:
    basedir: tomcat

spring:
  profiles:
    active: @profileActive@
  application:
    name: apocalypse-geek
  messages:
    basename: i18n/messages
    encoding: UTF-8
  redis:
    redisson:
      config: classpath:/redisson.yaml
  main:
    # ShardingSphere 需要自己创建数据源，和 Druid 数据源冲突，设置允许 bean 定义覆盖来避免报错
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      location: upload
