logging:
  config: classpath:logback-spring.xml

server:
  port: 31001

spring:
  profiles:
    active: @profileActive@
  application:
    name: apocalypse-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        # Add your routes here.
        - id: apocalypse-example
          uri: lb://apocalypse-example/
          predicates:
            - Path=/example-api/**
          filters:
            - SwaggerHeaderFilter
        - id: apocalypse-user
          uri: lb://apocalypse-user/
          predicates:
            - Path=/user-api/**
          filters:
            - SwaggerHeaderFilter

