#debug: true
logging:
  path: ./logs/
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: druid
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/apocalypse_example?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10000ms
  cloud:
    inetutils:
      ignored-interfaces: #忽略docker0网卡以及 veth开头的网卡
        - docker0
        - veth.*
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      log:
        switch-pid: true
    consul:
      enabled: true
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
        tags:
          - java
          - service
        health-check-path: ${server.servlet.context-path}/actuator/health
        instance-id: instance-${spring.cloud.client.ip-address}-${spring.application.name}-${server.port}
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        # 手动ACK 不开启自动ACK模式，目的是防止报错后未正确处理消息丢失，默认 为 none
        acknowledge-mode: manual
    virtual-host: apocalypse
  cache:
    type: redis
    redis:
      time-to-live: 300000ms

  shardingsphere:
    datasource:
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/apocalypse_example?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/apocalypse_example1?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
      names: ds0,ds1
    sharding:
#      default-database-strategy:
#        inline:
#          algorithm-expression: ds$->{user_id % 2}
#          sharding-column: user_id
      tables:
        # 单库分表
        t_order:
          actual-data-nodes: ds0.t_order_$->{0..9}
          table-strategy:
            inline:
              algorithm-expression: t_order_$->{order_id % 10}
              sharding-column: order_id
#        t_order_item:
#          actual-data-nodes: ds$->{0..1}.t_order_item_$->{0..1}
#          table-strategy:
#            inline:
#              algorithm-expression: t_order_item_$->{order_id % 2}
#              sharding-column: order_id
